### ISSUE TITLE
Comparison against Perl one-liners

### ISSUE THREAD

**Issue by sshine** [DanRyba253/smh#1]
I really like this tool; it has a jq feel to it. I'm generally using Perl one-liners for this, where jq works better when operating on nested structures.

Here's a comparison of the examples in the README against how I'd write similar Perl one-liners:

    # display all words longer than 3 characters
    smh 'words.if length>3|get' < input_file
    perl -nE '@m=$_=~/(\w{4,})/g;say"@m"' < input_file

    # capitalize all words
    smh 'words.[0]|over upper' <input_file
    perl -pE 's/\b(\w)/\U$1/g' < input_file

    # display the third word in lines that start with an asterisk
    smh 'lines.if startsWith "*".<words>.[2]|get' < input_file
    perl -nE '/^\*(?:\w+\s){2}(\w+)/ && say $1' < input_file

Although barely readable, Perl is already a string DSL.

What it doesn't do well is dealing with arbitrary structure in texts.

Perhaps some examples that imply some more structure would reveal where simple regex is beaten by combinators.

**Comment by DanRyba253** [comment]
Thank you. What kind of structures are you thinking of?

**Comment by sshine** [comment]
The example combinators suggest words and lines.

I feel those are often easily achieved by  `\w+`, `\b`, `\s+`, but sometimes deceivingly not.

Maybe extracting floating-point numbers or embedded JSON objects out of texts is an example of something that's text on the outset, but quickly becomes about something more. Importing any special-purpose parser for dealing with a substring is where a dense one-liner quickly becomes a full program squeezed into technically-one line. It's not so easy to use regex to mark when a JSON object begins and ends, it's much easier to apply a parser and try, but less elegant. So a DSL might help at that.

**Comment by DanRyba253** [comment]
smh now has JSON support and there are ways to extract floating numbers, so closing the issue.
