### ISSUE TITLE
Publish on Hackage

### ISSUE THREAD

**Issue by blamario** [DanRyba253/smh#3]
It's not hard to do and it would simplify the installation instructions. Also you'd get a hyperlinked Haddock documentation of the library for free.

**Comment by DanRyba253** [comment]
Yeah, I'll do that next. Trying to publish on aur right now.

**Comment by DanRyba253** [comment]
I need to get endorsed first. so...hopefully that happens at some point: https://hackage.haskell.org/user/danirybe/endorse

**Comment by DanRyba253** [comment]
Thank you, done. Closing the issue.
